version: '3'
services:
  app:
    image: "node:12.22.12"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app
    tty: true
    command: >
      bash -c "npm install && npm run watch"
